import { defineStore } from "pinia";
import axios from "@/plugins/axios.js";
export const useProductsStore = defineStore("products", {
  state: () => ({
    items: [],
    totalCount: 0,
    pageCount: 0,
    currentPage: 0,
    perPage: 0,
  }),
  actions: {
    getItems(page) {
      return new Promise(async (resolve, reject) => {
        try {
          // const response = await axios.get(
          //   `/api/v1/frontend/product/site?page=${page}`
          // );
          const response = {
            data: {
              status: true,
              data: {
                items: [
                  {
                      "id": 0,
                      "name": "adsf",
                      "category_id": null,
                      "brand_id": null,
                      "slug": "adsf",
                      "unit_price": 0,
                      "images": [
                          {
                              "path": "1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg",
                              "name": "9074.jpg_wh860.jpg",
                              "size": "315418",
                              "type": "image/jpeg",
                              "order": "",
                              "base_url": "http://localhost:8000/source",
                              "link": "http://192.168.1.113:8000/source/1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg"
                          }
                      ],
                      "brand": "",
                      "category": "",
                      "colors": [],
                      "rating": 0,
                      "product_meta": null,
                      "variants": [
                          {
                              "id": 28,
                              "name": "adsf",
                              "product_id": 21,
                              "product_asset_id": null,
                              "code": null,
                              "sku": "adsf",
                              "barcode": "dfdfd",
                              "meta_field": null,
                              "option_ids": null,
                              "custom_price": null,
                              "unit_price": 0,
                              "sll_price": 0,
                              "import_price": 0,
                              "inventory_management": null,
                              "inventory_policy": null,
                              "inventory_quantity": null,
                              "requires_shipping_address": null,
                              "unit_type": null,
                              "grams": null,
                              "weight": null,
                              "weight_type": "g",
                              "dimension": "",
                              "group_id": null,
                              "position": 0,
                              "created_at": null,
                              "updated_at": null,
                              "deleted_at": null,
                              "visible": null,
                              "status": 0,
                              "images": null,
                              "color_id": null,
                              "slug": "adsf"
                          }
                      ]
                  },
                  {
                      "id": 1,
                      "name": "adsf",
                      "category_id": null,
                      "brand_id": null,
                      "slug": "adsf",
                      "unit_price": 0,
                      "images": [
                          {
                              "path": "1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg",
                              "name": "9074.jpg_wh860.jpg",
                              "size": "315418",
                              "type": "image/jpeg",
                              "order": "",
                              "base_url": "http://localhost:8000/source",
                              "link": "http://192.168.1.113:8000/source/1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg"
                          }
                      ],
                      "brand": "",
                      "category": "",
                      "colors": [],
                      "rating": 0,
                      "product_meta": null,
                      "variants": [
                          {
                              "id": 28,
                              "name": "adsf",
                              "product_id": 21,
                              "product_asset_id": null,
                              "code": null,
                              "sku": "adsf",
                              "barcode": "dfdfd",
                              "meta_field": null,
                              "option_ids": null,
                              "custom_price": null,
                              "unit_price": 0,
                              "sll_price": 0,
                              "import_price": 0,
                              "inventory_management": null,
                              "inventory_policy": null,
                              "inventory_quantity": null,
                              "requires_shipping_address": null,
                              "unit_type": null,
                              "grams": null,
                              "weight": null,
                              "weight_type": "g",
                              "dimension": "",
                              "group_id": null,
                              "position": 0,
                              "created_at": null,
                              "updated_at": null,
                              "deleted_at": null,
                              "visible": null,
                              "status": 0,
                              "images": null,
                              "color_id": null,
                              "slug": "adsf"
                          }
                      ]
                  },
                  {
                      "id": 2,
                      "name": "adsf",
                      "category_id": null,
                      "brand_id": null,
                      "slug": "adsf",
                      "unit_price": 0,
                      "images": [
                          {
                              "path": "1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg",
                              "name": "9074.jpg_wh860.jpg",
                              "size": "315418",
                              "type": "image/jpeg",
                              "order": "",
                              "base_url": "http://localhost:8000/source",
                              "link": "http://192.168.1.113:8000/source/1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg"
                          }
                      ],
                      "brand": "",
                      "category": "",
                      "colors": [],
                      "rating": 0,
                      "product_meta": null,
                      "variants": [
                          {
                              "id": 28,
                              "name": "adsf",
                              "product_id": 21,
                              "product_asset_id": null,
                              "code": null,
                              "sku": "adsf",
                              "barcode": "dfdfd",
                              "meta_field": null,
                              "option_ids": null,
                              "custom_price": null,
                              "unit_price": 0,
                              "sll_price": 0,
                              "import_price": 0,
                              "inventory_management": null,
                              "inventory_policy": null,
                              "inventory_quantity": null,
                              "requires_shipping_address": null,
                              "unit_type": null,
                              "grams": null,
                              "weight": null,
                              "weight_type": "g",
                              "dimension": "",
                              "group_id": null,
                              "position": 0,
                              "created_at": null,
                              "updated_at": null,
                              "deleted_at": null,
                              "visible": null,
                              "status": 0,
                              "images": null,
                              "color_id": null,
                              "slug": "adsf"
                          }
                      ]
                  },
                  {
                      "id": 3,
                      "name": "adsf",
                      "category_id": null,
                      "brand_id": null,
                      "slug": "adsf",
                      "unit_price": 0,
                      "images": [
                          {
                              "path": "1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg",
                              "name": "9074.jpg_wh860.jpg",
                              "size": "315418",
                              "type": "image/jpeg",
                              "order": "",
                              "base_url": "http://localhost:8000/source",
                              "link": "http://192.168.1.113:8000/source/1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg"
                          }
                      ],
                      "brand": "",
                      "category": "",
                      "colors": [],
                      "rating": 0,
                      "product_meta": null,
                      "variants": [
                          {
                              "id": 28,
                              "name": "adsf",
                              "product_id": 21,
                              "product_asset_id": null,
                              "code": null,
                              "sku": "adsf",
                              "barcode": "dfdfd",
                              "meta_field": null,
                              "option_ids": null,
                              "custom_price": null,
                              "unit_price": 0,
                              "sll_price": 0,
                              "import_price": 0,
                              "inventory_management": null,
                              "inventory_policy": null,
                              "inventory_quantity": null,
                              "requires_shipping_address": null,
                              "unit_type": null,
                              "grams": null,
                              "weight": null,
                              "weight_type": "g",
                              "dimension": "",
                              "group_id": null,
                              "position": 0,
                              "created_at": null,
                              "updated_at": null,
                              "deleted_at": null,
                              "visible": null,
                              "status": 0,
                              "images": null,
                              "color_id": null,
                              "slug": "adsf"
                          }
                      ]
                  },
                  {
                      "id": 4,
                      "name": "adsf",
                      "category_id": null,
                      "brand_id": null,
                      "slug": "adsf",
                      "unit_price": 0,
                      "images": [
                          {
                              "path": "1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg",
                              "name": "9074.jpg_wh860.jpg",
                              "size": "315418",
                              "type": "image/jpeg",
                              "order": "",
                              "base_url": "http://localhost:8000/source",
                              "link": "http://192.168.1.113:8000/source/1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg"
                          }
                      ],
                      "brand": "",
                      "category": "",
                      "colors": [],
                      "rating": 0,
                      "product_meta": null,
                      "variants": [
                          {
                              "id": 28,
                              "name": "adsf",
                              "product_id": 21,
                              "product_asset_id": null,
                              "code": null,
                              "sku": "adsf",
                              "barcode": "dfdfd",
                              "meta_field": null,
                              "option_ids": null,
                              "custom_price": null,
                              "unit_price": 0,
                              "sll_price": 0,
                              "import_price": 0,
                              "inventory_management": null,
                              "inventory_policy": null,
                              "inventory_quantity": null,
                              "requires_shipping_address": null,
                              "unit_type": null,
                              "grams": null,
                              "weight": null,
                              "weight_type": "g",
                              "dimension": "",
                              "group_id": null,
                              "position": 0,
                              "created_at": null,
                              "updated_at": null,
                              "deleted_at": null,
                              "visible": null,
                              "status": 0,
                              "images": null,
                              "color_id": null,
                              "slug": "adsf"
                          }
                      ]
                  },
                  {
                      "id": 5,
                      "name": "adsf",
                      "category_id": null,
                      "brand_id": null,
                      "slug": "adsf",
                      "unit_price": 0,
                      "images": [
                          {
                              "path": "1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg",
                              "name": "9074.jpg_wh860.jpg",
                              "size": "315418",
                              "type": "image/jpeg",
                              "order": "",
                              "base_url": "http://localhost:8000/source",
                              "link": "http://192.168.1.113:8000/source/1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg"
                          }
                      ],
                      "brand": "",
                      "category": "",
                      "colors": [],
                      "rating": 0,
                      "product_meta": null,
                      "variants": [
                          {
                              "id": 28,
                              "name": "adsf",
                              "product_id": 21,
                              "product_asset_id": null,
                              "code": null,
                              "sku": "adsf",
                              "barcode": "dfdfd",
                              "meta_field": null,
                              "option_ids": null,
                              "custom_price": null,
                              "unit_price": 0,
                              "sll_price": 0,
                              "import_price": 0,
                              "inventory_management": null,
                              "inventory_policy": null,
                              "inventory_quantity": null,
                              "requires_shipping_address": null,
                              "unit_type": null,
                              "grams": null,
                              "weight": null,
                              "weight_type": "g",
                              "dimension": "",
                              "group_id": null,
                              "position": 0,
                              "created_at": null,
                              "updated_at": null,
                              "deleted_at": null,
                              "visible": null,
                              "status": 0,
                              "images": null,
                              "color_id": null,
                              "slug": "adsf"
                          }
                      ]
                  },
                  {
                      "id": 6,
                      "name": "adsf",
                      "category_id": null,
                      "brand_id": null,
                      "slug": "adsf",
                      "unit_price": 0,
                      "images": [
                          {
                              "path": "1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg",
                              "name": "9074.jpg_wh860.jpg",
                              "size": "315418",
                              "type": "image/jpeg",
                              "order": "",
                              "base_url": "http://localhost:8000/source",
                              "link": "http://192.168.1.113:8000/source/1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg"
                          }
                      ],
                      "brand": "",
                      "category": "",
                      "colors": [],
                      "rating": 0,
                      "product_meta": null,
                      "variants": [
                          {
                              "id": 28,
                              "name": "adsf",
                              "product_id": 21,
                              "product_asset_id": null,
                              "code": null,
                              "sku": "adsf",
                              "barcode": "dfdfd",
                              "meta_field": null,
                              "option_ids": null,
                              "custom_price": null,
                              "unit_price": 0,
                              "sll_price": 0,
                              "import_price": 0,
                              "inventory_management": null,
                              "inventory_policy": null,
                              "inventory_quantity": null,
                              "requires_shipping_address": null,
                              "unit_type": null,
                              "grams": null,
                              "weight": null,
                              "weight_type": "g",
                              "dimension": "",
                              "group_id": null,
                              "position": 0,
                              "created_at": null,
                              "updated_at": null,
                              "deleted_at": null,
                              "visible": null,
                              "status": 0,
                              "images": null,
                              "color_id": null,
                              "slug": "adsf"
                          }
                      ]
                  },
                  {
                      "id": 7,
                      "name": "adsf",
                      "category_id": null,
                      "brand_id": null,
                      "slug": "adsf",
                      "unit_price": 0,
                      "images": [
                          {
                              "path": "1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg",
                              "name": "9074.jpg_wh860.jpg",
                              "size": "315418",
                              "type": "image/jpeg",
                              "order": "",
                              "base_url": "http://localhost:8000/source",
                              "link": "http://192.168.1.113:8000/source/1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg"
                          }
                      ],
                      "brand": "",
                      "category": "",
                      "colors": [],
                      "rating": 0,
                      "product_meta": null,
                      "variants": [
                          {
                              "id": 28,
                              "name": "adsf",
                              "product_id": 21,
                              "product_asset_id": null,
                              "code": null,
                              "sku": "adsf",
                              "barcode": "dfdfd",
                              "meta_field": null,
                              "option_ids": null,
                              "custom_price": null,
                              "unit_price": 0,
                              "sll_price": 0,
                              "import_price": 0,
                              "inventory_management": null,
                              "inventory_policy": null,
                              "inventory_quantity": null,
                              "requires_shipping_address": null,
                              "unit_type": null,
                              "grams": null,
                              "weight": null,
                              "weight_type": "g",
                              "dimension": "",
                              "group_id": null,
                              "position": 0,
                              "created_at": null,
                              "updated_at": null,
                              "deleted_at": null,
                              "visible": null,
                              "status": 0,
                              "images": null,
                              "color_id": null,
                              "slug": "adsf"
                          }
                      ]
                  },
                  {
                      "id": 8,
                      "name": "adsf",
                      "category_id": null,
                      "brand_id": null,
                      "slug": "adsf",
                      "unit_price": 0,
                      "images": [
                          {
                              "path": "1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg",
                              "name": "9074.jpg_wh860.jpg",
                              "size": "315418",
                              "type": "image/jpeg",
                              "order": "",
                              "base_url": "http://localhost:8000/source",
                              "link": "http://192.168.1.113:8000/source/1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg"
                          }
                      ],
                      "brand": "",
                      "category": "",
                      "colors": [],
                      "rating": 0,
                      "product_meta": null,
                      "variants": [
                          {
                              "id": 28,
                              "name": "adsf",
                              "product_id": 21,
                              "product_asset_id": null,
                              "code": null,
                              "sku": "adsf",
                              "barcode": "dfdfd",
                              "meta_field": null,
                              "option_ids": null,
                              "custom_price": null,
                              "unit_price": 0,
                              "sll_price": 0,
                              "import_price": 0,
                              "inventory_management": null,
                              "inventory_policy": null,
                              "inventory_quantity": null,
                              "requires_shipping_address": null,
                              "unit_type": null,
                              "grams": null,
                              "weight": null,
                              "weight_type": "g",
                              "dimension": "",
                              "group_id": null,
                              "position": 0,
                              "created_at": null,
                              "updated_at": null,
                              "deleted_at": null,
                              "visible": null,
                              "status": 0,
                              "images": null,
                              "color_id": null,
                              "slug": "adsf"
                          }
                      ]
                  },
                  {
                      "id": 9,
                      "name": "adsf",
                      "category_id": null,
                      "brand_id": null,
                      "slug": "adsf",
                      "unit_price": 0,
                      "images": [
                          {
                              "path": "1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg",
                              "name": "9074.jpg_wh860.jpg",
                              "size": "315418",
                              "type": "image/jpeg",
                              "order": "",
                              "base_url": "http://localhost:8000/source",
                              "link": "http://192.168.1.113:8000/source/1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg"
                          }
                      ],
                      "brand": "",
                      "category": "",
                      "colors": [],
                      "rating": 0,
                      "product_meta": null,
                      "variants": [
                          {
                              "id": 28,
                              "name": "adsf",
                              "product_id": 21,
                              "product_asset_id": null,
                              "code": null,
                              "sku": "adsf",
                              "barcode": "dfdfd",
                              "meta_field": null,
                              "option_ids": null,
                              "custom_price": null,
                              "unit_price": 0,
                              "sll_price": 0,
                              "import_price": 0,
                              "inventory_management": null,
                              "inventory_policy": null,
                              "inventory_quantity": null,
                              "requires_shipping_address": null,
                              "unit_type": null,
                              "grams": null,
                              "weight": null,
                              "weight_type": "g",
                              "dimension": "",
                              "group_id": null,
                              "position": 0,
                              "created_at": null,
                              "updated_at": null,
                              "deleted_at": null,
                              "visible": null,
                              "status": 0,
                              "images": null,
                              "color_id": null,
                              "slug": "adsf"
                          }
                      ]
                  },
                  {
                      "id": 10,
                      "name": "adsf",
                      "category_id": null,
                      "brand_id": null,
                      "slug": "adsf",
                      "unit_price": 0,
                      "images": [
                          {
                              "path": "1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg",
                              "name": "9074.jpg_wh860.jpg",
                              "size": "315418",
                              "type": "image/jpeg",
                              "order": "",
                              "base_url": "http://localhost:8000/source",
                              "link": "http://192.168.1.113:8000/source/1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg"
                          }
                      ],
                      "brand": "",
                      "category": "",
                      "colors": [],
                      "rating": 0,
                      "product_meta": null,
                      "variants": [
                          {
                              "id": 28,
                              "name": "adsf",
                              "product_id": 21,
                              "product_asset_id": null,
                              "code": null,
                              "sku": "adsf",
                              "barcode": "dfdfd",
                              "meta_field": null,
                              "option_ids": null,
                              "custom_price": null,
                              "unit_price": 0,
                              "sll_price": 0,
                              "import_price": 0,
                              "inventory_management": null,
                              "inventory_policy": null,
                              "inventory_quantity": null,
                              "requires_shipping_address": null,
                              "unit_type": null,
                              "grams": null,
                              "weight": null,
                              "weight_type": "g",
                              "dimension": "",
                              "group_id": null,
                              "position": 0,
                              "created_at": null,
                              "updated_at": null,
                              "deleted_at": null,
                              "visible": null,
                              "status": 0,
                              "images": null,
                              "color_id": null,
                              "slug": "adsf"
                          }
                      ]
                  },
                  {
                      "id": 11,
                      "name": "adsf",
                      "category_id": null,
                      "brand_id": null,
                      "slug": "adsf",
                      "unit_price": 0,
                      "images": [
                          {
                              "path": "1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg",
                              "name": "9074.jpg_wh860.jpg",
                              "size": "315418",
                              "type": "image/jpeg",
                              "order": "",
                              "base_url": "http://localhost:8000/source",
                              "link": "http://192.168.1.113:8000/source/1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg"
                          }
                      ],
                      "brand": "",
                      "category": "",
                      "colors": [],
                      "rating": 0,
                      "product_meta": null,
                      "variants": [
                          {
                              "id": 28,
                              "name": "adsf",
                              "product_id": 21,
                              "product_asset_id": null,
                              "code": null,
                              "sku": "adsf",
                              "barcode": "dfdfd",
                              "meta_field": null,
                              "option_ids": null,
                              "custom_price": null,
                              "unit_price": 0,
                              "sll_price": 0,
                              "import_price": 0,
                              "inventory_management": null,
                              "inventory_policy": null,
                              "inventory_quantity": null,
                              "requires_shipping_address": null,
                              "unit_type": null,
                              "grams": null,
                              "weight": null,
                              "weight_type": "g",
                              "dimension": "",
                              "group_id": null,
                              "position": 0,
                              "created_at": null,
                              "updated_at": null,
                              "deleted_at": null,
                              "visible": null,
                              "status": 0,
                              "images": null,
                              "color_id": null,
                              "slug": "adsf"
                          }
                      ]
                  },
                  {
                      "id": 12,
                      "name": "adsf",
                      "category_id": null,
                      "brand_id": null,
                      "slug": "adsf",
                      "unit_price": 0,
                      "images": [
                          {
                              "path": "1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg",
                              "name": "9074.jpg_wh860.jpg",
                              "size": "315418",
                              "type": "image/jpeg",
                              "order": "",
                              "base_url": "http://localhost:8000/source",
                              "link": "http://192.168.1.113:8000/source/1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg"
                          }
                      ],
                      "brand": "",
                      "category": "",
                      "colors": [],
                      "rating": 0,
                      "product_meta": null,
                      "variants": [
                          {
                              "id": 28,
                              "name": "adsf",
                              "product_id": 21,
                              "product_asset_id": null,
                              "code": null,
                              "sku": "adsf",
                              "barcode": "dfdfd",
                              "meta_field": null,
                              "option_ids": null,
                              "custom_price": null,
                              "unit_price": 0,
                              "sll_price": 0,
                              "import_price": 0,
                              "inventory_management": null,
                              "inventory_policy": null,
                              "inventory_quantity": null,
                              "requires_shipping_address": null,
                              "unit_type": null,
                              "grams": null,
                              "weight": null,
                              "weight_type": "g",
                              "dimension": "",
                              "group_id": null,
                              "position": 0,
                              "created_at": null,
                              "updated_at": null,
                              "deleted_at": null,
                              "visible": null,
                              "status": 0,
                              "images": null,
                              "color_id": null,
                              "slug": "adsf"
                          }
                      ]
                  },
                  {
                    "id": 13,
                    "name": "adsf",
                    "category_id": null,
                    "brand_id": null,
                    "slug": "adsf",
                    "unit_price": 0,
                    "images": [
                        {
                            "path": "1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg",
                            "name": "9074.jpg_wh860.jpg",
                            "size": "315418",
                            "type": "image/jpeg",
                            "order": "",
                            "base_url": "http://localhost:8000/source",
                            "link": "http://192.168.1.113:8000/source/1\\mDHQrWEWOjO7D9Po8M40m5bAf-4zghpF.jpg"
                        }
                    ],
                    "brand": "",
                    "category": "",
                    "colors": [],
                    "rating": 0,
                    "product_meta": null,
                    "variants": [
                        {
                            "id": 28,
                            "name": "adsf",
                            "product_id": 21,
                            "product_asset_id": null,
                            "code": null,
                            "sku": "adsf",
                            "barcode": "dfdfd",
                            "meta_field": null,
                            "option_ids": null,
                            "custom_price": null,
                            "unit_price": 0,
                            "sll_price": 0,
                            "import_price": 0,
                            "inventory_management": null,
                            "inventory_policy": null,
                            "inventory_quantity": null,
                            "requires_shipping_address": null,
                            "unit_type": null,
                            "grams": null,
                            "weight": null,
                            "weight_type": "g",
                            "dimension": "",
                            "group_id": null,
                            "position": 0,
                            "created_at": null,
                            "updated_at": null,
                            "deleted_at": null,
                            "visible": null,
                            "status": 0,
                            "images": null,
                            "color_id": null,
                            "slug": "adsf"
                        }
                    ]
                }
              ],
                _links: {
                  self: {
                    href: "http://192.168.1.113:8080/api/v1/frontend/product/site/index?category=&page=1",
                  },
                  first: {
                    href: "http://192.168.1.113:8080/api/v1/frontend/product/site/index?category=&page=1",
                  },
                  last: {
                    href: "http://192.168.1.113:8080/api/v1/frontend/product/site/index?category=&page=1",
                  },
                },
                _meta: {
                  totalCount: 1,
                  pageCount: 1,
                  currentPage: 1,
                  perPage: 20,
                },
              },
              messages: "",
              code: 200,
            },
          };
          if (!response.data || !response.data.status) {
            throw new Error("Error");
          }
          this.items = response.data.data.items;
          this.totalCount = response.data.data._meta.totalCount;
          this.pageCount = response.data.data._meta.pageCount;
          this.currentPage = response.data.data._meta.currentPage;
          this.perPage = response.data.data._meta.perPage;
          resolve();
        } catch (error) {
          reject(error);
        }
      });
    },
  },
});
